from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

class ContextItem(BaseModel):
    id: Optional[str] = Field(default=None, description="Optional item id; if missing will be autogenerated")
    text: str
    metadata: Dict[str, Any] | None = None

class ContextBatch(BaseModel):
    session_id: str
    items: List[ContextItem]

class SearchRequest(BaseModel):
    session_id: str
    query: str
    top_k: int = 5
    metadata_filter: Dict[str, Any] | None = None
    keyword_bias: float = 0.0

class SearchHit(BaseModel):
    id: str
    text: str
    score: float
    metadata: Dict[str, Any] | None = None
    keyword_bonus: Optional[float] = None

class SearchResponse(BaseModel):
    results: List[SearchHit]

class HealthResponse(BaseModel):
    status: str
    sessions: int

class SessionInfo(BaseModel):
    session_id: str
    documents: int
    first_entry: Optional[str] = None
    last_entry: Optional[str] = None
    agents: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] | None = None

class SessionListResponse(BaseModel):
    sessions: List[SessionInfo]

class SessionDumpEntry(BaseModel):
    id: str
    text: str
    metadata: Dict[str, Any] | None = None

class SessionDumpResponse(BaseModel):
    session_id: str
    entries: List[SessionDumpEntry]

class PruneRequest(BaseModel):
    cutoff_iso: Optional[str] = Field(default=None, description="Optional ISO timestamp override; defaults to metadata expires_at values.")

class PruneResponse(BaseModel):
    session_id: str
    removed: int

class DashboardSummary(BaseModel):
    total_sessions: int
    total_documents: int
    by_agent: Dict[str, int]
    recent_sessions: List[Dict[str, Any]]
