@echo off
echo Testing AIONS server health...
powershell -Command "(Invoke-WebRequest -Uri 'http://127.0.0.1:9000/health' -UseBasicParsing).Content"
if %ERRORLEVEL% NEQ 0 (
    echo Server not running. Starting server...
    start /B powershell -Command "cd 'C:\Users\User\Desktop\AIONS_CBMS_RELEASE'; .\run_server.ps1"
    timeout /t 10
    echo Checking again...
    powershell -Command "(Invoke-WebRequest -Uri 'http://127.0.0.1:9000/health' -UseBasicParsing).Content"
)
echo Running deep conversation test...
powershell -ExecutionPolicy Bypass -File "C:\Users\User\Desktop\AIONS_CBMS_RELEASE\deep_conversation_test.ps1"